const canvas=document.querySelector('#game'), ctx=canvas.getContext('2d');
const W=540,H=960; let running=false, paused=false, last=0, distance=0, loot=0, lives=3, lane=0, targetLane=0, jump=0, jumpV=0, entities=[], spawnTimer=0, level=0, xp=120, sound=true;
const routes=[
 {name:'Eixample · Plaça Catalunya',sub:'Ruta 1 de 4 · 850 m',sky:'#8fd3ed',ground:'#66798a',landmarks:'eixample',target:850},
 {name:'Metro · Passeig de Gràcia',sub:'Ruta 2 de 4 · 1.100 m',sky:'#556c81',ground:'#46525c',landmarks:'metro',target:1100},
 {name:'Barceloneta · Passeig Marítim',sub:'Ruta 3 de 4 · 1.250 m',sky:'#81d4e9',ground:'#b88f68',landmarks:'beach',target:1250},
 {name:'Montjuïc · Mirador',sub:'Ruta final · 1.400 m',sky:'#e9a56f',ground:'#747268',landmarks:'montjuic',target:1400,final:true}
];
function el(id){return document.getElementById(id)} function route(){return routes[level%routes.length]}
function resize(){ const r=canvas.getBoundingClientRect(), d=devicePixelRatio||1; canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(canvas.width/W,0,0,canvas.height/H,0,0) } addEventListener('resize',resize);resize();
function rr(x,y,w,h,r,fill){ctx.fillStyle=fill;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
function text(str,x,y,size,color,align='center',font='Nunito'){ctx.fillStyle=color;ctx.font=`900 ${size}px ${font}`;ctx.textAlign=align;ctx.fillText(str,x,y)}
function trapezoid(y, bottomW, topW, color){let yy=y, top=y-100;ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(W/2-topW/2,top);ctx.lineTo(W/2+topW/2,top);ctx.lineTo(W/2+bottomW/2,yy);ctx.lineTo(W/2-bottomW/2,yy);ctx.fill()}
function drawScene(){let r=route();ctx.fillStyle=r.sky;ctx.fillRect(0,0,W,H); // sun
 ctx.fillStyle='#fff3be';ctx.beginPath();ctx.arc(440,108,48,0,7);ctx.fill();
 if(r.landmarks==='metro'){ctx.fillStyle='#39444e';ctx.fillRect(0,0,W,440);ctx.fillStyle='#61717c';for(let i=0;i<7;i++)ctx.fillRect(i*90+15,70,47,240); ctx.fillStyle='#121b25';ctx.fillRect(0,290,W,150);text('METRO',270,165,35,'#ffda44','center','400 Bebas Neue');}
 else {drawBuildings(r.landmarks);}
 trapezoid(H, 690,150,r.ground); for(let i=1;i<10;i++){let p=(i/10 + (distance%90)/900)%1,y=285+(p*p)*675,w=20+p*80;ctx.fillStyle='#e6dbc5';ctx.fillRect(W/2-w/2,y,w,Math.max(2,p*12))}
 // rails/curbs
 ctx.strokeStyle='#f3c55c';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(195,290);ctx.lineTo(48,960);ctx.moveTo(345,290);ctx.lineTo(492,960);ctx.stroke();
 for(let z=0;z<7;z++){let p=z/7, y=305+p*p*470, ww=150+p*400;ctx.fillStyle='#ffffff20';ctx.fillRect(W/2-ww/2,y,ww,2+p*4)}
}
function drawBuildings(kind){let colors=kind==='beach'?['#f5c473','#e28669','#f3d6ac']:kind==='montjuic'?['#6f8e70','#d9a56d','#7a8e72']:['#e9a06c','#f3c574','#d97863'];for(let i=0;i<8;i++){let side=i%2, x=side?360+i*20:-50-i*20, y=145+(i%3)*25, w=100+(i%2)*22,h=205-(i%3)*20;ctx.fillStyle=colors[i%3];ctx.fillRect(x,y,w,h);ctx.fillStyle='#234561';for(let q=0;q<3;q++)ctx.fillRect(x+18+q*27,y+35,12,32)}if(kind==='eixample'){ctx.fillStyle='#c78958';ctx.fillRect(35,175,94,140);ctx.fillStyle='#527766';ctx.beginPath();ctx.arc(82,132,55,0,7);ctx.fill();}if(kind==='beach'){ctx.fillStyle='#2eafc7';ctx.fillRect(0,267,W,40);for(let x=20;x<540;x+=100){ctx.fillStyle='#fff4d1';ctx.beginPath();ctx.arc(x,220,28,Math.PI,0);ctx.fill();}}if(kind==='montjuic'){ctx.fillStyle='#47754e';ctx.beginPath();ctx.arc(90,235,110,Math.PI,0);ctx.arc(440,235,135,Math.PI,0);ctx.fill();}}
function scaleFor(z){return .35+z*1.25} function posFor(e){let s=scaleFor(e.z), y=270+e.z*e.z*650,x=W/2+e.lane*135*s;return{x,y,s}}
function drawEntity(e){let {x,y,s}=posFor(e);ctx.save();ctx.translate(x,y);ctx.scale(s,s);if(e.type==='loot'){ctx.fillStyle='#ffd23f';ctx.beginPath();ctx.moveTo(0,-26);ctx.lineTo(20,0);ctx.lineTo(0,26);ctx.lineTo(-20,0);ctx.fill();ctx.fillStyle='#fff8e9';ctx.beginPath();ctx.arc(0,0,7,0,7);ctx.fill();}else if(e.type==='barrier'){ctx.fillStyle='#f5f0dc';ctx.fillRect(-38,-20,76,40);ctx.fillStyle='#ff6438';for(let i=-30;i<34;i+=22)ctx.fillRect(i,-20,10,40);ctx.fillStyle='#273950';ctx.fillRect(-46,20,92,11)}else {let politician=e.type==='politician'; // friendly stylized fictional adversary
 ctx.fillStyle=politician?'#d7b28e':['#e7b58d','#a96f54','#75452f'][e.variant%3];ctx.beginPath();ctx.arc(0,-52,20,0,7);ctx.fill();ctx.fillStyle='#26344b';ctx.beginPath();ctx.arc(0,-58,22,3.3,6.15);ctx.fill();ctx.fillStyle=politician?'#506a92':e.variant%2?'#25364b':'#6c3f84';rr(-28,-29,56,58,10,ctx.fillStyle);ctx.fillStyle='#273247';ctx.fillRect(-22,29,17,35);ctx.fillRect(5,29,17,35);if(politician){ctx.fillStyle='#e5b248';ctx.fillRect(25,-2,23,27);ctx.strokeStyle='#79592f';ctx.lineWidth=3;ctx.strokeRect(25,-2,23,27)}else{ctx.fillStyle='#ffdf52';ctx.beginPath();ctx.arc(30,-1,8,0,7);ctx.fill();}if(e.hit){ctx.globalAlpha=.8;ctx.fillStyle='#dff8fa';ctx.beginPath();ctx.arc(-38,-26,17,0,7);ctx.fill();ctx.beginPath();ctx.arc(-60,-40,10,0,7);ctx.fill();}}
 ctx.restore()}
function drawPlayer(){let x=W/2+lane*135,y=H-130-jump;ctx.save();ctx.translate(x,y);ctx.fillStyle='#273449';ctx.beginPath();ctx.arc(0,-68,23,0,7);ctx.fill();ctx.fillStyle='#e4a47f';ctx.beginPath();ctx.arc(0,-51,18,0,7);ctx.fill();rr(-30,-33,60,67,15,'#f5c142');ctx.fillStyle='#ffffff';ctx.fillRect(-18,-24,36,8);ctx.fillStyle='#23344b';ctx.fillRect(-23,33,18,37);ctx.fillRect(5,33,18,37);ctx.fillStyle='#f5f1df';ctx.fillRect(-29,67,27,9);ctx.fillRect(3,67,27,9); // spray
 ctx.fillStyle='#ff6438';ctx.fillRect(29,-18,13,27);ctx.fillStyle='#e8e7d8';ctx.fillRect(28,-22,15,6);ctx.restore()}
function draw(){drawScene();entities.sort((a,b)=>a.z-b.z).forEach(drawEntity);drawPlayer();if(running&&!paused){let r=route();text(`${Math.min(Math.floor(distance),r.target)} m / ${r.target} m`,270,45,13,'#fff','center');}}
function addEntity(){let r=route(), roll=Math.random(), type;if(roll<.34)type='loot';else if(roll<.5)type='barrier';else type=r.final&&Math.random()<.54?'politician':'enemy';entities.push({type,lane:Math.floor(Math.random()*3)-1,z:0,variant:Math.floor(Math.random()*3),hit:false});}
function update(dt){if(!running||paused)return; distance+=dt*.1;spawnTimer-=dt;if(spawnTimer<0){addEntity();spawnTimer=520+Math.random()*500}jump+=jumpV*dt;jumpV-=.0019*dt;if(jump<0){jump=0;jumpV=0}entities.forEach(e=>e.z+=dt*.00017);for(let i=entities.length-1;i>=0;i--){let e=entities[i];if(e.z>1.04){if(e.type==='loot'){}else if(!e.hit&&e.lane===lane&&jump<35){lives--;flash('¡CUIDADO!');updateHUD();if(lives<=0){finish(false);return}}entities.splice(i,1)}}if(distance>=route().target)finish(true);updateHUD()}
function action(){if(!running||paused)return;let best=entities.filter(e=>(e.type==='enemy'||e.type==='politician')&&!e.hit&&e.lane===lane&&e.z>.25&&e.z<.88).sort((a,b)=>b.z-a.z)[0];if(best){best.hit=true;loot+=best.type==='politician'?2:1;entities.push({type:'loot',lane:best.lane,z:best.z+.02});flash(best.type==='politician'?'¡TOMATE DIRECTO!':'¡RECUPERADO!')}else flash('¡APUNTA A UN OBJETIVO!')}
let flashTill=0,flashMsg='';function flash(msg){flashMsg=msg;flashTill=performance.now()+700}function hudFlash(){if(flashTill>performance.now()){text(flashMsg,270,180,17,'#fff8e9','center');}}
function loop(t){let dt=Math.min(40,t-last||16);last=t;update(dt);draw();hudFlash();requestAnimationFrame(loop)}requestAnimationFrame(loop);
function updateHUD(){el('lootHUD').textContent=loot;el('levelHUD').textContent=String(level+1).padStart(2,'0');document.querySelector('.life').innerHTML='<i></i>'.repeat(lives)}
function start(){running=true;paused=false;distance=0;loot=0;lives=3;entities=[];spawnTimer=250;el('menu').classList.add('hidden');el('result').classList.add('hidden');el('hud').classList.remove('hidden');el('pauseBtn').classList.remove('hidden');updateHUD()}
function finish(success){running=false;el('hud').classList.add('hidden');el('pauseBtn').classList.add('hidden');let gained=success?loot*25+100:loot*10;xp+=gained;el('resultKicker').textContent=success?'MISIÓN COMPLETADA':'RUTA INTERRUMPIDA';el('resultTitle').textContent=success?'¡DEVUELTO!':'¡A RECARGAR!';el('resultCopy').textContent=success?'Las pertenencias recuperadas vuelven a manos de su barrio.':'Has salvado parte del botín. Prueba otra vez con calma.';el('resultLoot').textContent=loot;el('resultXP').textContent='+'+gained;el('xpFill').style.width=(xp%400/4+10)+'%';el('levelupText').textContent='Nivel de corredor '+(Math.floor(xp/400)+1);el('nextBtn').textContent=success?(level===3?'VOLVER A LA PRIMERA RUTA':'SIGUIENTE RUTA  ›'):'INTENTAR DE NUEVO  ›';el('result').classList.remove('hidden');if(success)level=(level+1)%routes.length;}
function move(n){if(!running||paused)return;targetLane=Math.max(-1,Math.min(1,lane+n));lane=targetLane}function doJump(){if(running&&!paused&&jump===0)jumpV=.75}
el('playBtn').onclick=start;el('resumeBtn').onclick=()=>{paused=false;el('pause').classList.add('hidden')};el('restartBtn').onclick=start;el('nextBtn').onclick=start;el('menuBtn').onclick=()=>{el('result').classList.add('hidden');el('menu').classList.remove('hidden');updateMenu()};el('pauseBtn').onclick=()=>{if(running){paused=true;el('pause').classList.remove('hidden')}};el('leftBtn').onclick=()=>move(-1);el('rightBtn').onclick=()=>move(1);el('jumpBtn').onclick=doJump;el('actionBtn').onclick=action;el('soundBtn').onclick=()=>{sound=!sound;el('soundBtn').textContent=sound?'♪':'×'};
addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp',' '].includes(e.key))e.preventDefault();if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1);if(e.key==='ArrowUp')doJump();if(e.key===' ')action();if(e.key==='Escape')el('pauseBtn').click()});
let touchStart;canvas.addEventListener('pointerdown',e=>touchStart={x:e.clientX,y:e.clientY});canvas.addEventListener('pointerup',e=>{if(!touchStart)return;let dx=e.clientX-touchStart.x,dy=e.clientY-touchStart.y;if(Math.abs(dx)>40)move(dx>0?1:-1);else if(dy<-35)doJump();else action();touchStart=null});
function updateMenu(){el('routeTitle').textContent=route().name;el('routeText').textContent=route().sub} updateMenu();
